from typing import Sequence

from docx.blkcntnr import BlockItemContainer
from docx.enum.section import WD_SECTION
from docx.oxml.section import CT_SectPr

class Section:
    _sectPr: CT_SectPr
    @property
    def different_first_page_header_footer(self) -> bool: ...
    @property
    def even_page_footer(self) -> _Footer: ...
    @property
    def even_page_header(self) -> _Header: ...
    @property
    def first_page_footer(self) -> _Footer: ...
    @property
    def first_page_header(self) -> _Header: ...
    @property
    def footer(self) -> _Footer: ...
    @property
    def header(self) -> _Header: ...
    @property
    def start_type(self) -> WD_SECTION: ...

class Sections(Sequence[Section]): ...

class _BaseHeaderFooter(BlockItemContainer):
    @property
    def is_linked_to_previous(self) -> bool: ...

class _Footer(_BaseHeaderFooter): ...
class _Header(_BaseHeaderFooter): ...
