repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.3.0"
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
      - id: check-json
      - id: check-xml
      - id: end-of-file-fixer
        exclude: \.json$
        files: \.py$
      - id: trailing-whitespace
      - id: mixed-line-ending

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        args: ["--line-length=100"]
        language_version: python3

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.1
    hooks:
      - id: ruff
        args:
          ["--fix"]

  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        language_version: python3
