name: Version Bump

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: read

jobs:
  version-bump:
    if: github.event.pull_request.user.login == 'utic-renovate[bot]'
    uses: Unstructured-IO/infra/.github/workflows/version-bump.yml@main
    with:
      component-paths: '["."]'
      default-bump: patch
      update-changelog: true
      update-lockfile: true
      renovate-app-id: ${{ vars.RENOVATE_APP_ID }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      private-pypi-url: ${{ secrets.PRIVATE_PYPI_INDEX_URL }}
      renovate-app-private-key: ${{ secrets.RENOVATE_APP_PRIVATE_KEY }}
