CREATE DATABASE ingest_test;
USE ingest_test;

CREATE TABLE elements (
    id TEXT PRIMARY KEY,
    element_id TEXT,
    text TEXT,
    embeddings Vector(384),
    type TEXT,
    system TEXT,
    layout_width DECIMAL,
    layout_height DECIMAL,
    points TEXT,
    url TEXT,
    version TEXT,
    date_created TIMESTAMP,
    date_modified TIMESTAMP,
    date_processed TIMESTAMP,
    permissions_data TEXT,
    record_locator TEXT,
    category_depth INTEGER,
    parent_id TEXT,
    attached_filename TEXT,
    filetype TEXT,
    last_modified TIMESTAMP,
    file_directory TEXT,
    filename TEXT,
    languages TEXT,
    page_number TEXT,
    links TEXT,
    page_name TEXT,
    link_urls TEXT,
    link_texts TEXT,
    sent_from TEXT,
    sent_to TEXT,
    subject TEXT,
    section TEXT,
    header_footer_type TEXT,
    emphasized_text_contents TEXT,
    emphasized_text_tags TEXT,
    text_as_html TEXT,
    regex_metadata TEXT,
    detection_class_prob DECIMAL,
    is_continuation BOOLEAN
);

