# Dockerfile that approximates the CI image
#
# Mainly useful for updating test-ingest fixtures

FROM ubuntu:22.04

COPY scripts/setup_ubuntu.sh scripts/setup_ubuntu.sh

RUN bash scripts/setup_ubuntu.sh root


