services:
  pgvector:
    image: ankane/pgvector
    restart: always
    container_name: pgvector_dest
    ports:
     - 5433:5432
    environment:
      POSTGRES_DB: elements
      POSTGRES_USER: unstructured
      POSTGRES_PASSWORD: test
    volumes:
      - ./create-pgvector-schema.sql:/docker-entrypoint-initdb.d/init.sql
