from typing import Iterator

from pptx.shapes.base import BaseShape
from pptx.shared import ParentedElementProxy

class _BaseShapes(ParentedElementProxy): ...
class _BaseGroupShapes(_BaseShapes): ...
class NotesSlideShapes(_BaseShapes): ...

class SlideShapes(_BaseGroupShapes):
    def __iter__(self) -> Iterator[BaseShape]: ...
