
name: 'Base Cache Build'
description: 'Restore the base python cache for CI to use, recreate if not found'
inputs:
  python-version:
    description: 'python version associated with the cache'
    required: true
  check-only:
    description: 'if set, will not restore the cache if it exists'
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      if: steps.virtualenv-cache-restore.outputs.cache-hit != 'true'
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
    - name: Setup virtual environment (no cache hit)
      if: steps.virtualenv-cache-restore.outputs.cache-hit != 'true'
      shell: bash
      run: |
        python${{ inputs.python-version }} -m venv .venv
        source .venv/bin/activate
        [ ! -d "$NLTK_DATA" ] && mkdir "$NLTK_DATA"
        make install-ci