
name: 'Ingest Cache Build'
description: 'Restore ingest specific cache on top of base cache, recreate if not found'
inputs:
  python-version:
    description: 'python version associated with the cache'
    required: true
  check-only:
    description: 'if set, will not restore the cache if it exists'
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Restore base virtual environment
      if: 'true'
      uses: ./.github/actions/base-cache
      with:
        python-version: ${{ inputs.python-version }}
    - name: Set up Python ${{ inputs.python-version }}
      if: 'true'
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
    - name: Setup virtual environment (no cache hit)
      if: 'true'
      shell: bash
      run: |
        python${{ inputs.python-version }} -m venv .venv
        source .venv/bin/activate
        make install-all-ingest